services:
    postgres:
        container_name: postgres
        image: postgis/postgis:12-3.2
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
        network_mode: "container:devcontainer"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 1s
            timeout: 1s
            retries: 120

volumes:
    postgres-data: {}
